### ISSUE TITLE
`URI malformed` error

### ISSUE THREAD

**Issue by ehmicky** [Munter/netlify-plugin-subfont#40]
The following error happened in some builds:

```
Failed during font subsetting
populate transform: URI malformed 
    /opt/build/repo/node_modules/urltools/lib/index.js:140:18 Object.exports.fileUrlToFsPath
    /opt/build/repo/node_modules/assetgraph/lib/assets/Asset.js:1482:20 makeRelativeToCwdIfPossible
    /opt/build/repo/node_modules/assetgraph/lib/assets/Asset.js:1489:9 Image.get urlOrDescription [as urlOrDescription]
    /opt/build/repo/node_modules/assetgraph/lib/transforms/logEvents.js:57:53 outputMessage
    /opt/build/repo/node_modules/assetgraph/lib/transforms/logEvents.js:142:9 AssetGraph.<anonymous>
    events.js:198:13 AssetGraph.emit
    /opt/build/repo/node_modules/assetgraph/lib/AssetGraph.js:169:12 AssetGraph.warn
    /opt/build/repo/node_modules/assetgraph/lib/transforms/populate.js:42:22 processAsset
```

Do you know what the error might be?

**Comment by Munter** [comment]
Looks like we are encountering either an invalid URI, or `decodeURI` gets an unexpected character as part of the URI, which it throws on.

The stack indicates that something probably went wrong during population of the asset, so a warning is emitted, but the warning handler throws while attempting to create the error output while running https://github.com/assetgraph/urltools/blob/master/lib/index.js#L138-L148

It looks like we need to build in a few more safeguards, because at the very least our error handler should be able to display the relevant error message it attempted to.

@papandreou This seems like something for Assetgraph core
