### ISSUE TITLE
Error: `The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined`

### ISSUE THREAD

**Issue by ehmicky** [Munter/netlify-plugin-subfont#43]
The following error happens in some builds:

```
 ✔ 0.832 secs: populate
 ✔ 0.067 secs: checkIncompatibleTypes
 ✔ 0.005 secs: populate
/bin/sh: 1: pyftsubset: not found
 ℹ INFO: Local subsetting is not possible because fonttools are not installed. Falling back to only subsetting Google Fonts. Run `pip install fonttools brotli zopfli` to enable local font subsetting
 ℹ INFO: Unoptimised fonts:
- assets/webfonts/fa-solid-900.woff2
- assets/webfonts/fa-brands-400.woff2
 ⚠ WARN: Asset.rawSrc getter: Asset isn't loaded: [Eot/578 assets/webfonts/fa-regular-400.eot]

┌────────────────────────────────────────┐
│ Plugin "netlify-plugin-subfont" failed │
└────────────────────────────────────────┘

Error message
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    internal/crypto/hash.js:82:11 Hash.update
    /opt/buildhome/.netlify-build-plugins/node_modules/assetgraph/lib/assets/Asset.js:878:10 Eot.get md5Hex [as md5Hex]
    /opt/buildhome/.netlify-build-plugins/node_modules/subfont/lib/subsetFonts.js:1028:61 subsetFonts
    internal/process/task_queues.js:62:5 runNextTicks
    internal/timers.js:429:9 processImmediate
    /opt/buildhome/.netlify-build-plugins/node_modules/subfont/lib/subfont.js:150:24 async subfont
```

Do you know what the error might be?

**Comment by Munter** [comment]
Looks like the user has self-hosted fonts in `/assets/webfonts/*` and is linking to a non-existing `fa-regular.eot`in that folder. Something that easily happens when you copy a CSS snippet for font loading but your self-hosted files don't match.

This is obviously a bug. Subfont should recover gracefully from missing font assets by just skipping the work.

Another thing that sticks out is that the user runs self-hosted fonts, but didn't install pyftsubset, so apparently didn't read the last paragraph and code example in https://github.com/Munter/netlify-plugin-subfont#installation
Has there been any change in a plugins ability to install external dependencies like pyftsubset, so I could avoid people running into this resulting missing optimization?

**Comment by ehmicky** [comment]
Node dependencies are installed, but unfortunately not dependencies coming from other languages like Python at the moment :(

**Comment by Munter** [comment]
@papandreou I have tried recreating this condition in a test in subfont but have been unable to. It seem to be this call that triggers the condition: https://github.com/Munter/subfont/blob/master/lib/subsetFonts.js#L1036

We're not checking if the font assets is loaded, and we probably should. I'd really like to get a test in here instead of just blindly adding an early exit if the asset isn't loaded and hope for the best
